HTTP_404_INVALID_ARGUMENT=404
HTTP_SUCCESS=200
HTTP_401_UNAUTHRISED=401
HTTP_400_BADREQUEST=400
HOST=":9001"        # bind to port 9001 on all IPs.
DB_HOST="localhost" # connect to postgres on this host
DB_USER="postgres"  # postgres user
DB_PASS="example"   # postgres password
DB_NAME="userapi"   # database schema name
DB_TABLE="users"
TOKEN_EXPIRED=10 #Token wil be valid till 10 mins
